server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bench
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 200
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true