server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bench
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
